### ISSUE TITLE
Missing documentation for nergen

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/toad#4]
I want to train a new NER tagger, I figure ``nergen`` is the way to go, but can't really find any information. The ``--help`` is a bit cryptic. 

> nergen will convert a 'traditionally' IOB tagged corpus

How should the input be formatted?

**Comment by kosloot** [comment]
Well, did you try `man nergen` ?
And some information should be available in the frog manual too.

**Comment by kosloot** [comment]
@Irishx maybe documenting the Toad utils is related or included in the Frog documenting task?

**Comment by proycon** [comment]
Ah, it seems the  main problem is that man pages are not properly found in LaMachine virtualenv!  proycon/LaMachine#104

**Comment by kosloot** [comment]
That was because it was missing form the toad package.
fixed now!
